-- 清空現有技能庫 (保留結構，但移除所有舊資料)
TRUNCATE TABLE public.skills_library CASCADE;

-- 插入高品質的預設技能 (已翻譯為繁體中文)
INSERT INTO public.skills_library 
(name, display_name, description, category, tags, icon, author, version, is_official, is_public, is_active, source, external_id, skill_content, required_tools, created_at, updated_at)
VALUES
-- 1. Analytics & Data (資料分析)
(
    'csv-analysis',
    '資料分析助手',
    '自動化處理 CSV 檔案，進行樞紐分析、趨勢預測與視覺化圖表生成。',
    'analytics',
    ARRAY['data', 'csv', 'visualization'],
    '📊',
    'eternnoir',
    '1.2.0',
    true, true, true,
    'internal',
    'csv-analysis',
    E'# 資料分析助手\n\n## 角色定義\n你是一位資料分析專家，擅長處理 CSV 檔案並進行深度分析。\n\n## 核心功能\n- 自動化處理 CSV 檔案\n- 進行樞紐分析\n- 趨勢預測\n- 視覺化圖表生成\n\n## 使用方式\n協助使用者分析 CSV 資料，提供洞察與視覺化結果。',
    ARRAY['export_csv', 'generate_chart', 'calculate_statistics'],
    NOW(), NOW()
),
(
    'financial-report',
    '財務報表分析',
    '智能解讀資產負債表與損益表，自動標記關鍵財務風險與成長指標。',
    'analytics',
    ARRAY['finance', 'report', 'audit'],
    '💰',
    'fintech-lab',
    '2.0.1',
    false, true, true,
    'internal',
    'financial-report',
    E'# 財務報表分析\n\n## 角色定義\n你是一位財務分析師，擅長解讀財務報表並提供洞察。\n\n## 核心功能\n- 解讀資產負債表與損益表\n- 標記關鍵財務風險\n- 識別成長指標\n- 提供財務建議\n\n## 分析重點\n協助使用者理解財務數據，識別風險與機會。',
    ARRAY['query_business_data', 'calculate_statistics', 'generate_chart'],
    NOW(), NOW()
),
(
    'market-research',
    '市場趨勢探勘',
    '整合 Google Trends 與新聞 API，生成特定產業的每日市場動態報告。',
    'analytics',
    ARRAY['marketing', 'research', 'trends'],
    '📈',
    'growth-hackers',
    '1.0.5',
    false, true, true,
    'internal',
    'market-research',
    E'# 市場趨勢探勘\n\n## 角色定義\n你是一位市場研究專家，擅長分析市場趨勢與動態。\n\n## 核心功能\n- 整合 Google Trends 數據\n- 分析新聞 API 資訊\n- 生成市場動態報告\n- 識別產業趨勢\n\n## 使用方式\n協助使用者了解市場動態，提供趨勢分析報告。',
    ARRAY['web_search', 'generate_chart', 'export_csv'],
    NOW(), NOW()
),

-- 2. Marketing (行銷)
(
    'social-copywriter',
    '社群文案撰寫',
    '針對 FB、IG 與 LinkedIn 不同平台風格，自動生成高互動率的行銷貼文。',
    'marketing',
    ARRAY['copywriting', 'social-media', 'content'],
    '✍️',
    'copy-ai-team',
    '3.1.0',
    true, true, true,
    'internal',
    'social-copywriter',
    E'# 社群文案撰寫\n\n## 角色定義\n你是一位創意行銷文案專家，擅長撰寫吸引目標受眾的社群內容。\n\n## 核心功能\n- 針對不同平台（FB、IG、LinkedIn）撰寫貼文\n- 生成高互動率的行銷內容\n- 優化文案結構與風格\n\n## 使用方式\n協助使用者撰寫符合平台特色的行銷文案。',
    ARRAY['web_search'],
    NOW(), NOW()
),
(
    'seo-audit',
    'SEO 網站健檢',
    '分析網頁的 Meta 標籤、關鍵字密度與讀取速度，提供具體的 SEO 優化建議。',
    'marketing',
    ARRAY['seo', 'web', 'optimization'],
    '🔍',
    'web-masters',
    '1.5.2',
    false, true, true,
    'internal',
    'seo-audit',
    E'# SEO 網站健檢\n\n## 角色定義\n你是一位 SEO 專家，擅長分析網站並提供優化建議。\n\n## 核心功能\n- 分析 Meta 標籤\n- 檢查關鍵字密度\n- 評估讀取速度\n- 提供 SEO 優化建議\n\n## 使用方式\n協助使用者改善網站 SEO 表現。',
    ARRAY['web_search'],
    NOW(), NOW()
),
(
    'email-campaign',
    'EDM 行銷自動化',
    '設計個人化的電子郵件行銷旅程，包含歡迎信、購物車未結帳提醒等範本。',
    'marketing',
    ARRAY['email', 'automation', 'crm'],
    '📧',
    'mail-wizards',
    '2.2.0',
    false, true, true,
    'internal',
    'email-campaign',
    E'# EDM 行銷自動化\n\n## 角色定義\n你是一位電子郵件行銷專家，擅長設計自動化行銷旅程。\n\n## 核心功能\n- 設計個人化郵件範本\n- 建立自動化行銷流程\n- 優化郵件開啟率與點擊率\n\n## 使用方式\n協助使用者設計有效的電子郵件行銷活動。',
    ARRAY['send_email', 'query_business_data'],
    NOW(), NOW()
),

-- 3. Human Resources (人力資源)
(
    'resume-screener',
    '智慧履歷篩選',
    '根據職位描述 (JD) 自動評分候選人履歷，標註技能匹配度與潛在問題。',
    'hr',
    ARRAY['recruitment', 'resume', 'ai'],
    '👥',
    'hr-tech-solutions',
    '1.1.0',
    true, true, true,
    'internal',
    'resume-screener',
    E'# 智慧履歷篩選\n\n## 角色定義\n你是一位 HR 招募專家，擅長分析履歷並評估候選人適配度。\n\n## 核心功能\n- 根據職位描述評分履歷\n- 標註技能匹配度\n- 識別潛在問題\n- 提供招募建議\n\n## 使用方式\n協助 HR 快速篩選合適的候選人。',
    ARRAY['search_knowledge'],
    NOW(), NOW()
),
(
    'interview-coach',
    '面試模擬教練',
    '扮演嚴格的面試官，針對特定職位進行模擬面試並提供回答建議。',
    'hr',
    ARRAY['interview', 'coaching', 'career'],
    '🎤',
    'career-boost',
    '2.5.0',
    false, true, true,
    'internal',
    'interview-coach',
    E'# 面試模擬教練\n\n## 角色定義\n你是一位面試教練，協助候選人準備面試。\n\n## 核心功能\n- 進行模擬面試\n- 提供回答建議\n- 評估面試表現\n- 給予改進建議\n\n## 使用方式\n協助候選人準備面試，提升錄取機率。',
    ARRAY['search_knowledge'],
    NOW(), NOW()
),
(
    'onboarding-bot',
    '新員工入職引導',
    '自動化發送入職文件、帳號開通指引與公司文化介紹，減輕 HR 負擔。',
    'hr',
    ARRAY['onboarding', 'automation', 'guide'],
    '👋',
    'people-ops',
    '1.0.0',
    false, true, true,
    'internal',
    'onboarding-bot',
    E'# 新員工入職引導\n\n## 角色定義\n你是一位 HR 助理，協助新員工順利入職。\n\n## 核心功能\n- 發送入職文件\n- 提供帳號開通指引\n- 介紹公司文化\n- 回答常見問題\n\n## 使用方式\n自動化處理新員工入職流程，減輕 HR 負擔。',
    ARRAY['send_email', 'search_knowledge'],
    NOW(), NOW()
),

-- 4. Development (軟體開發)
(
    'git-expert',
    'Git 版本控制專家',
    '解決複雜的 Git 衝突，提供最佳的 Commit Message 建議與分支管理策略。',
    'general',
    ARRAY['git', 'version-control', 'devops'],
    '🌲',
    'git-gurus',
    '4.0.0',
    true, true, true,
    'internal',
    'git-expert',
    E'# Git 版本控制專家\n\n## 角色定義\n你是一位 Git 專家，擅長解決版本控制問題。\n\n## 核心功能\n- 解決 Git 衝突\n- 提供 Commit Message 建議\n- 分支管理策略\n- 版本控制最佳實踐\n\n## 使用方式\n協助開發者解決 Git 相關問題。',
    ARRAY[]::TEXT[],
    NOW(), NOW()
),
(
    'code-reviewer',
    '代碼審查助手',
    '自動檢測程式碼中的安全漏洞、效能瓶頸與風格不一致問題 (支援 TS/Python)。',
    'general',
    ARRAY['code-review', 'security', 'quality'],
    '👓',
    'clean-coders',
    '2.1.5',
    false, true, true,
    'internal',
    'code-reviewer',
    E'# 代碼審查助手\n\n## 角色定義\n你是一位代碼審查專家，擅長發現程式碼問題。\n\n## 核心功能\n- 檢測安全漏洞\n- 識別效能瓶頸\n- 檢查風格一致性\n- 提供改進建議\n\n## 使用方式\n協助開發者提升程式碼品質。',
    ARRAY[]::TEXT[],
    NOW(), NOW()
),
(
    'api-doc-gen',
    'API 文件生成器',
    '讀取程式碼註解與路由定義，自動生成標準的 Swagger/OpenAPI 文件。',
    'general',
    ARRAY['api', 'documentation', 'swagger'],
    '📝',
    'doc-tools',
    '1.3.0',
    false, true, true,
    'internal',
    'api-doc-gen',
    E'# API 文件生成器\n\n## 角色定義\n你是一位技術文件專家，擅長生成 API 文件。\n\n## 核心功能\n- 讀取程式碼註解\n- 解析路由定義\n- 生成 Swagger/OpenAPI 文件\n- 維護文件一致性\n\n## 使用方式\n協助開發者自動生成 API 文件。',
    ARRAY[]::TEXT[],
    NOW(), NOW()
),

-- 5. Legal & Finance (法律與財務)
(
    'contract-policy-check',
    '法律文件審閱',
    '快速掃描合約內容，標示出可能對我不利的條款與模糊地帶。',
    'legal',
    ARRAY['contract', 'legal', 'risk'],
    '⚖️',
    'legal-ai',
    '1.8.0',
    true, true, true,
    'internal',
    'contract-policy-check',
    E'# 法律文件審閱\n\n## 角色定義\n你是一位法務助手，協助審閱商業文件。\n\n## 核心功能\n- 掃描合約內容\n- 標示不利條款\n- 識別模糊地帶\n- 提供風險評估\n\n## 使用方式\n協助使用者審閱法律文件，降低風險。',
    ARRAY['search_knowledge', 'summarize_document'],
    NOW(), NOW()
),
(
    'invoice-processor',
    '發票單據辨識',
    'OCR 辨識各類發票與收據，自動分類並匯出至會計系統格式。',
    'finance',
    ARRAY['ocr', 'invoice', 'accounting'],
    '🧾',
    'fin-automators',
    '2.0.0',
    false, true, true,
    'internal',
    'invoice-processor',
    E'# 發票單據辨識\n\n## 角色定義\n你是一位財務自動化專家，擅長處理發票與單據。\n\n## 核心功能\n- OCR 辨識發票與收據\n- 自動分類單據\n- 匯出至會計系統格式\n- 驗證單據正確性\n\n## 使用方式\n協助財務人員自動化處理單據。',
    ARRAY['export_csv', 'query_business_data'],
    NOW(), NOW()
),

-- 6. Sales (銷售)
(
    'sales-script-gen',
    '銷售話術指南',
    '針對不同客戶類型與抗拒點，即時生成說服力極強的應對話術。',
    'sales',
    ARRAY['sales', 'script', 'negotiation'],
    '💼',
    'sales-force-one',
    '3.2.0',
    true, true, true,
    'internal',
    'sales-script-gen',
    E'# 銷售話術指南\n\n## 角色定義\n你是一位銷售顧問，協助制定有效的銷售話術。\n\n## 核心功能\n- 分析客戶類型\n- 處理抗拒點\n- 生成應對話術\n- 優化銷售策略\n\n## 使用方式\n協助銷售人員提升成交率。',
    ARRAY['search_knowledge', 'query_business_data'],
    NOW(), NOW()
),
(
    'lead-scorer',
    '潛在客戶評分',
    '根據客戶行為數據，預測成單機率並排列優先聯絡順序。',
    'sales',
    ARRAY['crm', 'leads', 'prediction'],
    '🎯',
    'sales-intel',
    '1.1.2',
    false, true, true,
    'internal',
    'lead-scorer',
    E'# 潛在客戶評分\n\n## 角色定義\n你是一位銷售分析師，協助評估潛在客戶價值。\n\n## 核心功能\n- 分析客戶行為數據\n- 預測成單機率\n- 排列優先聯絡順序\n- 提供銷售建議\n\n## 使用方式\n協助銷售團隊優先處理高價值潛在客戶。',
    ARRAY['query_business_data', 'calculate_statistics'],
    NOW(), NOW()
),

-- 7. Productivity (生產力)
(
    'meeting-minutes',
    '會議記錄整理',
    '將冗長的會議錄音轉錄稿，總結為條列式的決策事項與待辦清單 (Action Items)。',
    'general',
    ARRAY['meeting', 'summary', 'efficiency'],
    '📝',
    'office-hero',
    '2.8.0',
    true, true, true,
    'internal',
    'meeting-minutes',
    E'# 會議記錄整理\n\n## 角色定義\n你是一位會議記錄專家，協助整理會議內容。\n\n## 核心功能\n- 整理會議錄音轉錄稿\n- 總結決策事項\n- 建立待辦清單\n- 追蹤行動項目\n\n## 使用方式\n協助使用者快速整理會議記錄。',
    ARRAY['create_task', 'send_email', 'summarize_document'],
    NOW(), NOW()
),
(
    'calendar-optimizer',
    '行事曆智慧排程',
    '分析會議碎片時間，自動安排專注工作時段 (Focus Time) 與會議最佳化。',
    'general',
    ARRAY['calendar', 'scheduling', 'time-management'],
    '📅',
    'time-master',
    '1.5.0',
    false, true, true,
    'internal',
    'calendar-optimizer',
    E'# 行事曆智慧排程\n\n## 角色定義\n你是一位時間管理專家，協助優化行事曆安排。\n\n## 核心功能\n- 分析會議碎片時間\n- 安排專注工作時段\n- 優化會議排程\n- 提升時間效率\n\n## 使用方式\n協助使用者更有效地管理時間。',
    ARRAY['create_task'],
    NOW(), NOW()
),
(
    'email-prioritizer',
    '收件匣優先級排序',
    '自動將 Email 分類為「緊急」、「待辦」與「電子報」，讓你專注重要訊息。',
    'general',
    ARRAY['email', 'organization', 'filters'],
    '📥',
    'inbox-zero',
    '1.0.5',
    false, true, true,
    'internal',
    'email-prioritizer',
    E'# 收件匣優先級排序\n\n## 角色定義\n你是一位郵件管理專家，協助整理收件匣。\n\n## 核心功能\n- 分類郵件（緊急、待辦、電子報）\n- 設定優先級\n- 過濾不重要郵件\n- 提升處理效率\n\n## 使用方式\n協助使用者專注處理重要郵件。',
    ARRAY[]::TEXT[],
    NOW(), NOW()
),

-- 8. Operations (營運)
(
    'sop-generator',
    'SOP 標準流程生成',
    '輸入粗略的操作步驟，自動擴寫為格式標準、易於遵循的 SOP 文件。',
    'operations',
    ARRAY['sop', 'process', 'documentation'],
    '📋',
    'process-ninja',
    '1.2.0',
    true, true, true,
    'internal',
    'sop-generator',
    E'# SOP 標準流程生成\n\n## 角色定義\n你是一位流程文件專家，協助建立標準作業程序。\n\n## 核心功能\n- 擴寫操作步驟\n- 建立標準格式\n- 確保易於遵循\n- 優化流程效率\n\n## 使用方式\n協助使用者建立完整的 SOP 文件。',
    ARRAY['search_knowledge'],
    NOW(), NOW()
),
(
    'inventory-forecast',
    '庫存需求預測',
    '根據歷史銷售數據與季節性因素，預測下個月的最佳進貨量。',
    'operations',
    ARRAY['inventory', 'supply-chain', 'prediction'],
    '📦',
    'supply-chain-ui',
    '2.1.0',
    false, true, true,
    'internal',
    'inventory-forecast',
    E'# 庫存需求預測\n\n## 角色定義\n你是一位供應鏈分析師，協助預測庫存需求。\n\n## 核心功能\n- 分析歷史銷售數據\n- 考慮季節性因素\n- 預測最佳進貨量\n- 優化庫存管理\n\n## 使用方式\n協助使用者做出更準確的進貨決策。',
    ARRAY['query_business_data', 'calculate_statistics', 'generate_chart'],
    NOW(), NOW()
),

-- 9. Customer Support (客服)
(
    'ticket-classifier',
    '客服工單分類',
    '自動判讀客戶問題類型 (如退款、技術支援、功能建議) 並分派給對應人員。',
    'support',
    ARRAY['ticket', 'classification', 'automation'],
    '🏷️',
    'support-ai',
    '1.4.0',
    true, true, true,
    'internal',
    'ticket-classifier',
    E'# 客服工單分類\n\n## 角色定義\n你是一位客服系統專家，協助自動分類工單。\n\n## 核心功能\n- 判讀客戶問題類型\n- 自動分類工單\n- 分派給對應人員\n- 提升處理效率\n\n## 使用方式\n協助客服團隊快速處理客戶問題。',
    ARRAY['search_knowledge', 'create_task'],
    NOW(), NOW()
),
(
    'chatbot-flow',
    '客戶服務標準流程',
    '提供專業的客服應對流程，從歡迎語到客訴處理，確保一致的服務品質。',
    'support',
    ARRAY['chatbot', 'flow', 'cs'],
    '🎧',
    'cs-experts',
    '3.0.0',
    false, true, true,
    'internal',
    'chatbot-flow',
    E'# 客戶服務標準流程\n\n## 角色定義\n你是一位客服專家，提供專業的服務流程。\n\n## 核心功能\n- 標準歡迎語\n- 問題處理流程\n- 客訴處理機制\n- 確保服務品質\n\n## 使用方式\n協助客服人員提供一致的服務體驗。',
    ARRAY['search_knowledge', 'send_email'],
    NOW(), NOW()
),

-- 10. Others (其他)
(
    'translation-pro',
    '專業多國語言翻譯',
    '支援 50+ 國語言的精準翻譯，特別針對商務書信與技術文件優化。',
    'general',
    ARRAY['translation', 'language', 'global'],
    '🌐',
    'polyglot-tech',
    '4.5.0',
    false, true, true,
    'internal',
    'translation-pro',
    E'# 專業多國語言翻譯\n\n## 角色定義\n你是一位專業翻譯專家，擅長多國語言翻譯。\n\n## 核心功能\n- 支援 50+ 國語言\n- 商務書信翻譯\n- 技術文件翻譯\n- 保持語境與專業術語\n\n## 使用方式\n協助使用者進行精準的專業翻譯。',
    ARRAY[]::TEXT[],
    NOW(), NOW()
);
